###
# CoffeeDoc example documentation #

This is a module-level docstring, and will be displayed at the top of the module documentation.
Documentation generated by [CoffeeDoc](http://github.com/omarkhan/coffeedoc)
###

window.FirehoseJS = {}

FirehoseJS.rootFor = (server) ->
  FirehoseJS.client.serverAddress server