###
This is a module-level docstring, and will be displayed at the top of the module documentation.
Documentation generated by [CoffeeDoc](http://github.com/omarkhan/coffeedoc)
###

window.FirehoseJS = {}


###
@param    server [string] The name of the server. Possible values: 'API', 'browser', 'billing', 'frhio', 'marketing', 'settings'
@return   [string] The root url of the server based on the current environement.
@example  Create a URL to the login page of the browser app.
  "#{FirehoseJS.rootFor('browser')/home/login"
###
FirehoseJS.rootFor = (server) ->
  FirehoseJS.client.serverAddress server
  
  
###
@param    service [string] The name of the service. Possible values: 'pusher', 'stripe'
@return   [string] The token/key used for that service's library.
###
FirehoseJS.tokenFor = (service) ->
  FirehoseJS.client.serviceToken service
  
  
###
Used to determine the current environment.
@return [Hash] A hash of all possible environments and only the current environment will be defined. So you can do `FirehoseJS.env.production?` in coffeescript.
###
FirehoseJS.env = ->
  FirehoseJS.client._currentEnvironment()